### ISSUE TITLE
Present Donate: 20180325 企业赞助 (贝贝集团) 3000元

### ISSUE THREAD

**Issue by EarlyH** [NodeParty-China/Node-OpenSource-Foundation#65]
Logo：
![image](https://user-images.githubusercontent.com/1768041/54892728-9ffec380-4eed-11e9-8725-9e40a00932ce.png)

URL：
https://www.beibei.com.cn/

**Comment by xinyu198736** [comment]
![image](https://user-images.githubusercontent.com/897401/54893928-2ff33c00-4ef3-11e9-98cd-b2b18a763eb3.png)
已收到并记录
